name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      - uses: julia-actions/setup-julia@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: coverallsapp/github-action@v2 # Updated to Coveralls v2
        with:
          file: lcov.info # Specify the path to the coverage file
          github-token: ${{ secrets.GITHUB_TOKEN }} # Default GitHub token, do not store in secrets manually
