name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Julia (specify your Julia version)
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1

      # Step 3: Install dependencies (using the local environment)
      - name: Install dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.build()'

      # Step 4: Run tests with coverage enabled and generate LCOV
      - name: Run tests with coverage
        run: |
          julia --project=. -e '
            using Pkg;
            Pkg.test(coverage=true);
            using Coverage;
            lcov = process_folder();
            isdir("coverage") || mkpath("coverage");
            Coverage.writefile("coverage/lcov.info", lcov);
          '

      # Step 5: Upload coverage to Coveralls
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v1
        with:
          path-to-lcov: coverage/lcov.info
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}    
    
