name: QuantLib CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  quantlib-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2

      # Step 3: Install dependencies in the main and test environments
      - name: Install main and test dependencies
        run: |
          # Instantiate the main project environment
          julia --project=. -e '
            using Pkg;
            Pkg.instantiate();
            Pkg.build();
          '
          
          # Instantiate the test project environment (which depends on the main)
          julia --project=test/ -e '
            using Pkg;
            Pkg.develop(path=".");
            Pkg.instantiate();
            Pkg.build();
          '

      # Step 4: Install QuantLib.py
      - name: Install QuantLib.py
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install QuantLib-Python

      # Step 5: Run QuantLib compatibility tests with custom macro in test environment
      - name: Run QuantLib compatibility tests
        working-directory: test
        run: |
          julia --project=. -e '
            using TestItemRunner
            using DerivativesPricer
            @run_package_tests filter=ti -> occursin("quantlib", ti.filename)
          '
